# https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.14"
  jobs:
    create_environment:
      - asdf plugin add uv
      - asdf install uv 0.9.30
      - asdf global uv 0.9.30
      - cd docs && UV_PROJECT_ENVIRONMENT=$READTHEDOCS_VIRTUALENV_PATH uv venv
    install:
      - cd docs && UV_PROJECT_ENVIRONMENT=$READTHEDOCS_VIRTUALENV_PATH uv sync --frozen

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true
