---
secrets:
  ## You can either set these secrets in a file named .env in this directory, or
  ## change these from "environment:" to "file:" with a path to store them on
  ## disk.  Be sure that files, if you use them, do not contain trailing
  ## newlines!
  ##
  ## You may also add additional secrets here, prefixed with zulip__, (and also
  ## in the "secrets:" block inside the "zulip" service, below) in order to
  ## propagate them into Zulip's /etc/zulip/zulip-secrets.conf
  ##
  ## --> https://docs.docker.com/reference/compose-file/secrets/
  ##     https://docs.docker.com/compose/how-tos/use-secrets/
  zulip__postgres_password:
    ## Note that you need to do a manual `ALTER ROLE` query if you
    ## change this on a system after booting the postgres container
    ## the first time on a host.  Instructions are available in README.md.
    environment: "ZULIP__POSTGRES_PASSWORD"
  zulip__memcached_password:
    environment: "ZULIP__MEMCACHED_PASSWORD"
  zulip__rabbitmq_password:
    environment: "ZULIP__RABBITMQ_PASSWORD"
  zulip__redis_password:
    environment: "ZULIP__REDIS_PASSWORD"
  zulip__secret_key:
    environment: "ZULIP__SECRET_KEY"
  zulip__email_password:
    environment: "ZULIP__EMAIL_PASSWORD"

services:
  zulip:
    build:
      args:
        ## If you want to build zulip from a different repo/branch, you can
        ## change these and run:
        ##
        ##  docker compose build zulip
        ZULIP_GIT_URL: https://github.com/zulip/zulip.git
        ZULIP_GIT_REF: "11.5"
    environment:
      ## See https://github.com/zulip/docker-zulip#configuration for
      ## details on this section and how to discover the many
      ## additional settings that are supported here.
      ##
      ## The following two settings are required:
      SETTING_EXTERNAL_HOST: "zulip.example.com"
      SETTING_ZULIP_ADMINISTRATOR: "zulip-admin@example.com"

      ## Most deploys do SSL termination outside of the container; Zulip
      ## defaults to only serving traffic over HTTP. If you'd like this
      ## container to do its own SSL termination, you may uncomment this to set
      ## up an auto-renewed Lets Encrypt certificate inside the container, or
      ## set it to "self-signed" to have Zulip generate a self-signed
      ## certificate.  In either of these cases, the container will only serve
      ## traffic over port 443.
      ##
      # CERTIFICATES: "certbot"

      ## If you're using a reverse proxy (as is required if you leave
      ## CERTIFICATES unset), you will also need to provide the comma-separated
      ## set of IP addresses (or CIDR ranges) to trust here.
      ##
      ## --> https://zulip.readthedocs.io/en/stable/production/reverse-proxies.html
      ##
      # LOADBALANCER_IPS: "10.0.0.0/8"
      ## Alternately, you can default to trusting the Docker gateway IP:
      # TRUST_GATEWAY_IP: True

      ## Outgoing email settings
      ##
      ## --> https://zulip.readthedocs.io/en/stable/production/email.html
      ##
      # SETTING_EMAIL_HOST: "smtp.example.com"
      # SETTING_EMAIL_HOST_USER: "noreply@example.com"
      # SETTING_EMAIL_PORT: "587"
      # SETTING_EMAIL_USE_SSL: False
      # SETTING_EMAIL_USE_TLS: True

      ## Uncomment to enable the incoming email gateway.  You will need to
      ## ensure that email to emaildomain.example.com is routed to this host
      ## (e.g. via MX record)
      ##
      ## --> https://zulip.readthedocs.io/en/stable/production/email-gateway.html
      ##
      # SETTING_EMAIL_GATEWAY_PATTERN: "%s@emaildomain.example.com"

      ## A comma-separated list of authentication backends to enable.  Note that
      ## this ZULIP_AUTH_BACKENDS takes the place of
      ## SETTING_AUTHENTICATION_BACKENDS.  This defaults to just
      ## EmailAuthBackend.
      ##
      ## --> https://zulip.readthedocs.io/en/stable/production/authentication-methods.html
      ##
      # ZULIP_AUTH_BACKENDS: "EmailAuthBackend,GoogleAuthBackend"

      ## Uncomment this when configuring the mobile push notifications service.
      ## After setting these, you will need to register the server:
      ##
      ##   docker compose exec -it -u zulip zulip /home/zulip/deployments/current/manage.py register_server
      ##
      ## --> https://zulip.readthedocs.io/en/stable/production/mobile-push-notifications.html
      ##
      # SETTING_ZULIP_SERVICE_PUSH_NOTIFICATIONS: True
      # SETTING_ZULIP_SERVICE_SUBMIT_USAGE_STATISTICS: True

      ## By default, files uploaded by users and profile pictures are
      ## stored directly on the Zulip server. You can configure files
      ## to be stored in Amazon S3 or a compatible data store
      ## here.
      ##
      ## If you want to use the S3 backend, you must set
      ## SETTING_LOCAL_UPLOADS_DIR to None as well as configuring the
      ## other fields.
      ##
      ## --> https://zulip.readthedocs.io/en/stable/production/upload-backends.html
      ##
      # SETTING_LOCAL_UPLOADS_DIR: "None"
      # SETTING_S3_AUTH_UPLOADS_BUCKET: ""
      # SETTING_S3_AVATAR_BUCKET: ""
      # SETTING_S3_ENDPOINT_URL: "None"
      # SETTING_S3_REGION: "None"

      ## For a complete list of possible settings, see:
      ## --> https://github.com/zulip/zulip/blob/11.x/zproject/prod_settings_template.py
    secrets:
      ## Add any additional zulip__ secrets that you defined above.
      []
