---
name: Lint markdown files prettier

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - run: npm install && npx prettier --write "**/*.md" ".*/**.md"
      - name: Check for any diff
        run: |
          if ! git diff HEAD --exit-code; then
            echo "Changes found!"
            git status
            git diff HEAD
            exit 1
          fi
