---
name: Lint markdown files prettier

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - run: npm install && npx prettier --write "**/*.md" ".*/**.md"
      - name: Check for any diff
        run: |
          if ! git diff HEAD --exit-code; then
            echo "Changes found!"
            git status
            git diff HEAD
            exit 1
          fi
