---
name: Spelling

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  spelling:
    name: Spellcheck with Typos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Spell Check Repo
        uses: crate-ci/typos@512fc24f32f44ab01972217aaaf3dc86ec234d53 # v1.50.2
