name: Test Docker Build

on:
  push:
    branches:
      - heroku-support
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Build Docker image
        run: docker build -t my-zulip-heroku-test .
